-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.33 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table winroad.countries
CREATE TABLE IF NOT EXISTS `countries` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `iso2` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=247 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table winroad.countries: ~245 rows (approximately)
/*!40000 ALTER TABLE `countries` DISABLE KEYS */;
INSERT INTO `countries` (`id`, `iso2`, `name`, `created_at`, `updated_at`) VALUES
	(1, 'AF', 'Afghanistan', NULL, NULL),
	(2, 'AL', 'Albania', NULL, NULL),
	(3, 'DZ', 'Algeria', NULL, NULL),
	(4, 'AS', 'American Samoa', NULL, NULL),
	(5, 'AD', 'Andorra', NULL, NULL),
	(6, 'AO', 'Angola', NULL, NULL),
	(7, 'AI', 'Anguilla', NULL, NULL),
	(8, 'AQ', 'Antarctica', NULL, NULL),
	(9, 'AG', 'Antigua And Barbuda', NULL, NULL),
	(10, 'AR', 'Argentina', NULL, NULL),
	(11, 'AM', 'Armenia', NULL, NULL),
	(12, 'AW', 'Aruba', NULL, NULL),
	(13, 'AU', 'Australia', NULL, NULL),
	(14, 'AT', 'Austria', NULL, NULL),
	(15, 'AZ', 'Azerbaijan', NULL, NULL),
	(16, 'BS', 'Bahamas The', NULL, NULL),
	(17, 'BH', 'Bahrain', NULL, NULL),
	(18, 'BD', 'Bangladesh', NULL, NULL),
	(19, 'BB', 'Barbados', NULL, NULL),
	(20, 'BY', 'Belarus', NULL, NULL),
	(21, 'BE', 'Belgium', NULL, NULL),
	(22, 'BZ', 'Belize', NULL, NULL),
	(23, 'BJ', 'Benin', NULL, NULL),
	(24, 'BM', 'Bermuda', NULL, NULL),
	(25, 'BT', 'Bhutan', NULL, NULL),
	(26, 'BO', 'Bolivia', NULL, NULL),
	(27, 'BA', 'Bosnia and Herzegovina', NULL, NULL),
	(28, 'BW', 'Botswana', NULL, NULL),
	(29, 'BV', 'Bouvet Island', NULL, NULL),
	(30, 'BR', 'Brazil', NULL, NULL),
	(31, 'IO', 'British Indian Ocean Territory', NULL, NULL),
	(32, 'BN', 'Brunei', NULL, NULL),
	(33, 'BG', 'Bulgaria', NULL, NULL),
	(34, 'BF', 'Burkina Faso', NULL, NULL),
	(35, 'BI', 'Burundi', NULL, NULL),
	(36, 'KH', 'Cambodia', NULL, NULL),
	(37, 'CM', 'Cameroon', NULL, NULL),
	(38, 'CA', 'Canada', NULL, NULL),
	(39, 'CV', 'Cape Verde', NULL, NULL),
	(40, 'KY', 'Cayman Islands', NULL, NULL),
	(41, 'CF', 'Central African Republic', NULL, NULL),
	(42, 'TD', 'Chad', NULL, NULL),
	(43, 'CL', 'Chile', NULL, NULL),
	(44, 'CN', 'China', NULL, NULL),
	(45, 'CX', 'Christmas Island', NULL, NULL),
	(46, 'CC', 'Cocos (Keeling) Islands', NULL, NULL),
	(47, 'CO', 'Colombia', NULL, NULL),
	(48, 'KM', 'Comoros', NULL, NULL),
	(49, 'CG', 'Congo', NULL, NULL),
	(50, 'CD', 'Congo The Democratic Republic Of The', NULL, NULL),
	(51, 'CK', 'Cook Islands', NULL, NULL),
	(52, 'CR', 'Costa Rica', NULL, NULL),
	(53, 'CI', 'Cote D\'Ivoire (Ivory Coast)', NULL, NULL),
	(54, 'HR', 'Croatia (Hrvatska)', NULL, NULL),
	(55, 'CU', 'Cuba', NULL, NULL),
	(56, 'CY', 'Cyprus', NULL, NULL),
	(57, 'CZ', 'Czech Republic', NULL, NULL),
	(58, 'DK', 'Denmark', NULL, NULL),
	(59, 'DJ', 'Djibouti', NULL, NULL),
	(60, 'DM', 'Dominica', NULL, NULL),
	(61, 'DO', 'Dominican Republic', NULL, NULL),
	(62, 'TP', 'East Timor', NULL, NULL),
	(63, 'EC', 'Ecuador', NULL, NULL),
	(64, 'EG', 'Egypt', NULL, NULL),
	(65, 'SV', 'El Salvador', NULL, NULL),
	(66, 'GQ', 'Equatorial Guinea', NULL, NULL),
	(67, 'ER', 'Eritrea', NULL, NULL),
	(68, 'EE', 'Estonia', NULL, NULL),
	(69, 'ET', 'Ethiopia', NULL, NULL),
	(70, 'XA', 'External Territories of Australia', NULL, NULL),
	(71, 'FK', 'Falkland Islands', NULL, NULL),
	(72, 'FO', 'Faroe Islands', NULL, NULL),
	(73, 'FJ', 'Fiji Islands', NULL, NULL),
	(74, 'FI', 'Finland', NULL, NULL),
	(75, 'FR', 'France', NULL, NULL),
	(76, 'GF', 'French Guiana', NULL, NULL),
	(77, 'PF', 'French Polynesia', NULL, NULL),
	(78, 'TF', 'French Southern Territories', NULL, NULL),
	(79, 'GA', 'Gabon', NULL, NULL),
	(80, 'GM', 'Gambia The', NULL, NULL),
	(81, 'GE', 'Georgia', NULL, NULL),
	(82, 'DE', 'Germany', NULL, NULL),
	(83, 'GH', 'Ghana', NULL, NULL),
	(84, 'GI', 'Gibraltar', NULL, NULL),
	(85, 'GR', 'Greece', NULL, NULL),
	(86, 'GL', 'Greenland', NULL, NULL),
	(87, 'GD', 'Grenada', NULL, NULL),
	(88, 'GP', 'Guadeloupe', NULL, NULL),
	(89, 'GU', 'Guam', NULL, NULL),
	(90, 'GT', 'Guatemala', NULL, NULL),
	(91, 'XU', 'Guernsey and Alderney', NULL, NULL),
	(92, 'GN', 'Guinea', NULL, NULL),
	(93, 'GW', 'Guinea-Bissau', NULL, NULL),
	(94, 'GY', 'Guyana', NULL, NULL),
	(95, 'HT', 'Haiti', NULL, NULL),
	(96, 'HM', 'Heard and McDonald Islands', NULL, NULL),
	(97, 'HN', 'Honduras', NULL, NULL),
	(98, 'HK', 'Hong Kong S.A.R.', NULL, NULL),
	(99, 'HU', 'Hungary', NULL, NULL),
	(100, 'IS', 'Iceland', NULL, NULL),
	(101, 'IN', 'India', NULL, NULL),
	(102, 'ID', 'Indonesia', NULL, NULL),
	(103, 'IR', 'Iran', NULL, NULL),
	(104, 'IQ', 'Iraq', NULL, NULL),
	(105, 'IE', 'Ireland', NULL, NULL),
	(106, 'IL', 'Israel', NULL, NULL),
	(107, 'IT', 'Italy', NULL, NULL),
	(108, 'JM', 'Jamaica', NULL, NULL),
	(109, 'JP', 'Japan', NULL, NULL),
	(110, 'XJ', 'Jersey', NULL, NULL),
	(111, 'JO', 'Jordan', NULL, NULL),
	(112, 'KZ', 'Kazakhstan', NULL, NULL),
	(113, 'KE', 'Kenya', NULL, NULL),
	(114, 'KI', 'Kiribati', NULL, NULL),
	(115, 'KP', 'Korea North', NULL, NULL),
	(116, 'KR', 'Korea South', NULL, NULL),
	(117, 'KW', 'Kuwait', NULL, NULL),
	(118, 'KG', 'Kyrgyzstan', NULL, NULL),
	(119, 'LA', 'Laos', NULL, NULL),
	(120, 'LV', 'Latvia', NULL, NULL),
	(121, 'LB', 'Lebanon', NULL, NULL),
	(122, 'LS', 'Lesotho', NULL, NULL),
	(123, 'LR', 'Liberia', NULL, NULL),
	(124, 'LY', 'Libya', NULL, NULL),
	(125, 'LI', 'Liechtenstein', NULL, NULL),
	(126, 'LT', 'Lithuania', NULL, NULL),
	(127, 'LU', 'Luxembourg', NULL, NULL),
	(128, 'MO', 'Macau S.A.R.', NULL, NULL),
	(129, 'MK', 'Macedonia', NULL, NULL),
	(130, 'MG', 'Madagascar', NULL, NULL),
	(131, 'MW', 'Malawi', NULL, NULL),
	(132, 'MY', 'Malaysia', NULL, NULL),
	(133, 'MV', 'Maldives', NULL, NULL),
	(134, 'ML', 'Mali', NULL, NULL),
	(135, 'MT', 'Malta', NULL, NULL),
	(136, 'XM', 'Man (Isle of)', NULL, NULL),
	(137, 'MH', 'Marshall Islands', NULL, NULL),
	(138, 'MQ', 'Martinique', NULL, NULL),
	(139, 'MR', 'Mauritania', NULL, NULL),
	(140, 'MU', 'Mauritius', NULL, NULL),
	(141, 'YT', 'Mayotte', NULL, NULL),
	(142, 'MX', 'Mexico', NULL, NULL),
	(143, 'FM', 'Micronesia', NULL, NULL),
	(144, 'MD', 'Moldova', NULL, NULL),
	(145, 'MC', 'Monaco', NULL, NULL),
	(146, 'MN', 'Mongolia', NULL, NULL),
	(147, 'MS', 'Montserrat', NULL, NULL),
	(148, 'MA', 'Morocco', NULL, NULL),
	(149, 'MZ', 'Mozambique', NULL, NULL),
	(150, 'MM', 'Myanmar', NULL, NULL),
	(151, 'NA', 'Namibia', NULL, NULL),
	(152, 'NR', 'Nauru', NULL, NULL),
	(153, 'NP', 'Nepal', NULL, NULL),
	(154, 'AN', 'Netherlands Antilles', NULL, NULL),
	(155, 'NL', 'Netherlands The', NULL, NULL),
	(156, 'NC', 'New Caledonia', NULL, NULL),
	(157, 'NZ', 'New Zealand', NULL, NULL),
	(158, 'NI', 'Nicaragua', NULL, NULL),
	(159, 'NE', 'Niger', NULL, NULL),
	(161, 'NU', 'Niue', NULL, NULL),
	(162, 'NF', 'Norfolk Island', NULL, NULL),
	(163, 'MP', 'Northern Mariana Islands', NULL, NULL),
	(164, 'NO', 'Norway', NULL, NULL),
	(165, 'OM', 'Oman', NULL, NULL),
	(166, 'PK', 'Pakistan', NULL, NULL),
	(167, 'PW', 'Palau', NULL, NULL),
	(168, 'PS', 'Palestinian Territory Occupied', NULL, NULL),
	(169, 'PA', 'Panama', NULL, NULL),
	(170, 'PG', 'Papua new Guinea', NULL, NULL),
	(171, 'PY', 'Paraguay', NULL, NULL),
	(172, 'PE', 'Peru', NULL, NULL),
	(173, 'PH', 'Philippines', NULL, NULL),
	(174, 'PN', 'Pitcairn Island', NULL, NULL),
	(175, 'PL', 'Poland', NULL, NULL),
	(176, 'PT', 'Portugal', NULL, NULL),
	(177, 'PR', 'Puerto Rico', NULL, NULL),
	(178, 'QA', 'Qatar', NULL, NULL),
	(179, 'RE', 'Reunion', NULL, NULL),
	(180, 'RO', 'Romania', NULL, NULL),
	(181, 'RU', 'Russia', NULL, NULL),
	(182, 'RW', 'Rwanda', NULL, NULL),
	(183, 'SH', 'Saint Helena', NULL, NULL),
	(184, 'KN', 'Saint Kitts And Nevis', NULL, NULL),
	(185, 'LC', 'Saint Lucia', NULL, NULL),
	(186, 'PM', 'Saint Pierre and Miquelon', NULL, NULL),
	(187, 'VC', 'Saint Vincent And The Grenadines', NULL, NULL),
	(188, 'WS', 'Samoa', NULL, NULL),
	(189, 'SM', 'San Marino', NULL, NULL),
	(190, 'ST', 'Sao Tome and Principe', NULL, NULL),
	(191, 'SA', 'Saudi Arabia', NULL, NULL),
	(192, 'SN', 'Senegal', NULL, NULL),
	(193, 'RS', 'Serbia', NULL, NULL),
	(194, 'SC', 'Seychelles', NULL, NULL),
	(195, 'SL', 'Sierra Leone', NULL, NULL),
	(196, 'SG', 'Singapore', NULL, NULL),
	(197, 'SK', 'Slovakia', NULL, NULL),
	(198, 'SI', 'Slovenia', NULL, NULL),
	(199, 'XG', 'Smaller Territories of the UK', NULL, NULL),
	(200, 'SB', 'Solomon Islands', NULL, NULL),
	(201, 'SO', 'Somalia', NULL, NULL),
	(202, 'ZA', 'South Africa', NULL, NULL),
	(203, 'GS', 'South Georgia', NULL, NULL),
	(204, 'SS', 'South Sudan', NULL, NULL),
	(205, 'ES', 'Spain', NULL, NULL),
	(206, 'LK', 'Sri Lanka', NULL, NULL),
	(207, 'SD', 'Sudan', NULL, NULL),
	(208, 'SR', 'Suriname', NULL, NULL),
	(209, 'SJ', 'Svalbard And Jan Mayen Islands', NULL, NULL),
	(210, 'SZ', 'Swaziland', NULL, NULL),
	(211, 'SE', 'Sweden', NULL, NULL),
	(212, 'CH', 'Switzerland', NULL, NULL),
	(213, 'SY', 'Syria', NULL, NULL),
	(214, 'TW', 'Taiwan', NULL, NULL),
	(215, 'TJ', 'Tajikistan', NULL, NULL),
	(216, 'TZ', 'Tanzania', NULL, NULL),
	(217, 'TH', 'Thailand', NULL, NULL),
	(218, 'TG', 'Togo', NULL, NULL),
	(219, 'TK', 'Tokelau', NULL, NULL),
	(220, 'TO', 'Tonga', NULL, NULL),
	(221, 'TT', 'Trinidad And Tobago', NULL, NULL),
	(222, 'TN', 'Tunisia', NULL, NULL),
	(223, 'TR', 'Turkey', NULL, NULL),
	(224, 'TM', 'Turkmenistan', NULL, NULL),
	(225, 'TC', 'Turks And Caicos Islands', NULL, NULL),
	(226, 'TV', 'Tuvalu', NULL, NULL),
	(227, 'UG', 'Uganda', NULL, NULL),
	(228, 'UA', 'Ukraine', NULL, NULL),
	(229, 'AE', 'United Arab Emirates', NULL, NULL),
	(230, 'GB', 'United Kingdom', NULL, NULL),
	(231, 'US', 'United States', NULL, NULL),
	(232, 'UM', 'United States Minor Outlying Islands', NULL, NULL),
	(233, 'UY', 'Uruguay', NULL, NULL),
	(234, 'UZ', 'Uzbekistan', NULL, NULL),
	(235, 'VU', 'Vanuatu', NULL, NULL),
	(236, 'VA', 'Vatican City State (Holy See)', NULL, NULL),
	(237, 'VE', 'Venezuela', NULL, NULL),
	(238, 'VN', 'Vietnam', NULL, NULL),
	(239, 'VG', 'Virgin Islands (British)', NULL, NULL),
	(240, 'VI', 'Virgin Islands (US)', NULL, NULL),
	(241, 'WF', 'Wallis And Futuna Islands', NULL, NULL),
	(242, 'EH', 'Western Sahara', NULL, NULL),
	(243, 'YE', 'Yemen', NULL, NULL),
	(244, 'YU', 'Yugoslavia', NULL, NULL),
	(245, 'ZM', 'Zambia', NULL, NULL),
	(246, 'ZW', 'Zimbabwe', NULL, NULL);
/*!40000 ALTER TABLE `countries` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
